"""M5.9 General Engineering Agent foundational contracts."""

from forge.general_engineering.errors import (
    EngineeringContractError,
    EngineeringEvidenceError,
    EngineeringPolicyError,
    EngineeringProviderError,
    EngineeringRepairError,
    EngineeringScopeError,
    GeneralEngineeringError,
)
from forge.general_engineering.identifiers import (
    change_plan_identifier,
    change_requirement_identifier,
    change_set_identifier,
    deterministic_engineering_identifier,
    edit_operation_identifier,
    engineering_evidence_identifier,
    engineering_request_identifier,
    repair_proposal_identifier,
    repository_evidence_identifier,
    validation_outcome_identifier,
    validation_plan_identifier,
)
from forge.general_engineering.models import (
    ChangePlan,
    ChangeRequirement,
    ChangeSpecification,
    EditOperation,
    EngineeringContext,
    EngineeringEvidence,
    EngineeringRequest,
    FileChangePlan,
    GeneratedChangeSet,
    RelevantFile,
    RelevantSymbol,
    RepairProposal,
    RepositoryEvidence,
    ValidationOutcome,
    ValidationPlan,
)
from forge.general_engineering.normalization import (
    normalize_optional_items,
    normalize_repository_path,
    normalize_text,
)
from forge.general_engineering.policies import (
    EngineeringLimits,
    EngineeringSafetyPolicy,
    EngineeringScopePolicy,
    GeneralEngineeringPolicy,
    is_forbidden_path,
)
from forge.general_engineering.protocols import EngineeringProvider
from forge.general_engineering.request_builder import (
    build_engineering_request,
)
from forge.general_engineering.request_understanding import (
    EngineeringRequestUnderstandingService,
    RequestUnderstandingResult,
    engineering_request_understanding_service,
)
from forge.general_engineering.requirement_extractor import (
    extract_change_requirements,
)
from forge.general_engineering.states import (
    EditOperationType,
    EngineeringRisk,
    EngineeringTerminalStatus,
    EvidenceType,
    RepairDisposition,
    ValidationStatus,
)

__all__ = [
    "ChangePlan",
    "ChangeRequirement",
    "ChangeSpecification",
    "EditOperation",
    "EditOperationType",
    "EngineeringContext",
    "EngineeringContractError",
    "EngineeringEvidence",
    "EngineeringEvidenceError",
    "EngineeringLimits",
    "EngineeringPolicyError",
    "EngineeringProvider",
    "EngineeringProviderError",
    "EngineeringRepairError",
    "EngineeringRequest",
    "EngineeringRequestUnderstandingService",
    "EngineeringRisk",
    "EngineeringSafetyPolicy",
    "EngineeringScopeError",
    "EngineeringScopePolicy",
    "EngineeringTerminalStatus",
    "EvidenceType",
    "FileChangePlan",
    "GeneralEngineeringError",
    "GeneralEngineeringPolicy",
    "GeneratedChangeSet",
    "RelevantFile",
    "RelevantSymbol",
    "RepairDisposition",
    "RepairProposal",
    "RepositoryEvidence",
    "RequestUnderstandingResult",
    "ValidationOutcome",
    "ValidationPlan",
    "ValidationStatus",
    "build_engineering_request",
    "change_plan_identifier",
    "change_requirement_identifier",
    "change_set_identifier",
    "deterministic_engineering_identifier",
    "edit_operation_identifier",
    "engineering_evidence_identifier",
    "engineering_request_identifier",
    "engineering_request_understanding_service",
    "extract_change_requirements",
    "is_forbidden_path",
    "normalize_optional_items",
    "normalize_repository_path",
    "normalize_text",
    "repair_proposal_identifier",
    "repository_evidence_identifier",
    "validation_outcome_identifier",
    "validation_plan_identifier",
]