"""Deterministic Markdown report rendering."""

from collections import Counter
from datetime import UTC, datetime

from forge.models.audit import AuditResult, Finding


def _items(values: list[str], empty: str = "None detected.") -> str:
    return "\n".join(f"- `{value}`" for value in values) if values else empty


class AuditReportRenderer:
    """Render an audit result into the Version 0.1 report suite."""

    def render(self, result: AuditResult) -> dict[str, str]:
        """Return report filenames mapped to complete content."""
        inventory = result.inventory
        timestamp = datetime.now(UTC).isoformat()
        header = f"<!-- Generated by Aerion ERP Engineering Agent v0.1 at {timestamp} -->"
        return {
            "PROJECT_SUMMARY.md": f"""{header}
# Project Summary

- Repository: `{result.repository}`
- Files scanned: {len(inventory.files)}
- Technologies detected: {", ".join(inventory.technologies) or "None"}
- Findings: {len(result.findings)}
- Audit duration: {(result.completed_at - result.started_at).total_seconds():.3f} seconds

## Architecture Areas

- Backend files: {len(inventory.backend_files)}
- Frontend files: {len(inventory.frontend_files)}
- Database migrations: {len(inventory.migrations)}
- API files: {len(inventory.api_files)}
- Route files: {len(inventory.route_files)}
- Test files: {len(inventory.test_files)}
""",
            "TECH_STACK.md": f"""{header}
# Technology Stack

## Technologies

{_items(inventory.technologies)}

## Languages by File Count

{_items([f"{name}: {count}" for name, count in sorted(inventory.languages.items())])}

## Package Managers

{_items(inventory.package_managers)}

## Build Commands

{_items(inventory.build_commands)}

## Test Commands

{_items(inventory.test_commands)}
""",
            "MODULE_INVENTORY.md": f"""{header}
# Module Inventory

## Backend

{_items(inventory.backend_files)}

## Frontend

{_items(inventory.frontend_files)}

## APIs

{_items(inventory.api_files)}

## Routes

{_items(inventory.route_files)}

## Database Migrations

{_items(inventory.migrations)}

## Tests

{_items(inventory.test_files)}
""",
            "PROJECT_ARCHITECTURE.md": f"""{header}
# Project Architecture

## Configuration

{_items(inventory.configuration)}

## Environment Files

{_items(inventory.environment_files)}

## Docker

{_items(inventory.docker_files)}

## Continuous Integration

{_items(inventory.ci_files)}

## Documentation

{_items(inventory.documentation)}

## Dependency Overview

- Declared dependencies: {len(result.dependency_graph.nodes)}
- Dependency edges: {len(result.dependency_graph.edges)}
""",
            "IMPLEMENTATION_BACKLOG.md": self._backlog(header, result.findings),
        }

    @staticmethod
    def _backlog(header: str, findings: list[Finding]) -> str:
        priority = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
        ordered = sorted(
            findings,
            key=lambda item: (priority.get(item.severity, 5), item.path or "", item.line or 0),
        )
        counts = Counter(item.severity for item in findings)
        lines = [header, "# Implementation Backlog", "", "## Summary", ""]
        lines.extend(f"- {level.title()}: {counts[level]}" for level in priority if counts[level])
        if not findings:
            lines.extend(["- No actionable findings detected.", ""])
        lines.extend(["", "## Prioritized Items", ""])
        for index, finding in enumerate(ordered, start=1):
            location = ""
            if finding.path:
                location = f" — `{finding.path}`"
                if finding.line:
                    location += f":{finding.line}"
            lines.extend(
                [
                    f"### {index}. [{finding.severity.upper()}] {finding.category}",
                    "",
                    f"{finding.message}{location}",
                    "",
                ]
            )
        return "\n".join(lines)
