"""M3.8 Unified Agent Runtime public API."""

from forge.agent_runtime.errors import (
    AgentRuntimeApprovalError,
    AgentRuntimeCapabilityError,
    AgentRuntimeConfigurationError,
    AgentRuntimeError,
    AgentRuntimeExecutionError,
    AgentRuntimePersistenceError,
    AgentRuntimePolicyError,
    AgentRuntimeRecoveryError,
    AgentRuntimeReportError,
    AgentRuntimeStateError,
    AgentRuntimeValidationError,
)
from forge.agent_runtime.identifiers import (
    agent_checkpoint_identifier,
    agent_event_identifier,
    agent_request_identifier,
    agent_session_identifier,
    agent_stage_identifier,
    stable_identifier,
)
from forge.agent_runtime.models import (
    AgentApproval,
    AgentCapability,
    AgentCheckpoint,
    AgentEvent,
    AgentEventType,
    AgentObjective,
    AgentRuntimePolicy,
    AgentRuntimeRequest,
    AgentSession,
    AgentSessionStatus,
    AgentStage,
    AgentStageResult,
    AgentStageStatus,
    ApprovalKind,
)
from forge.agent_runtime.policies import (
    approval_required,
    require_approval,
    resolve_repository_root,
    validate_request,
    validate_self_modification,
)

__all__ = [
    "AgentApproval",
    "AgentCapability",
    "AgentCheckpoint",
    "AgentEvent",
    "AgentEventType",
    "AgentObjective",
    "AgentRuntimeApprovalError",
    "AgentRuntimeCapabilityError",
    "AgentRuntimeConfigurationError",
    "AgentRuntimeError",
    "AgentRuntimeExecutionError",
    "AgentRuntimePersistenceError",
    "AgentRuntimePolicy",
    "AgentRuntimePolicyError",
    "AgentRuntimeRecoveryError",
    "AgentRuntimeReportError",
    "AgentRuntimeRequest",
    "AgentRuntimeStateError",
    "AgentRuntimeValidationError",
    "AgentSession",
    "AgentSessionStatus",
    "AgentStage",
    "AgentStageResult",
    "AgentStageStatus",
    "ApprovalKind",
    "agent_checkpoint_identifier",
    "agent_event_identifier",
    "agent_request_identifier",
    "agent_session_identifier",
    "agent_stage_identifier",
    "approval_required",
    "require_approval",
    "resolve_repository_root",
    "stable_identifier",
    "validate_request",
    "validate_self_modification",
]